### ISSUE TITLE
this error on every game install on lutris flatpak

### ISSUE THREAD

**Issue by gasinvein** [RobLoach/net.lutris.Lutris#20]
this error on every game install on lutris flatpak
![Screenshot from 2019-04-01 17-48-24](https://user-images.githubusercontent.com/40650341/55326883-74a84580-54a6-11e9-8bff-47694c587238.png)

_Originally posted by @jatin-cbs in https://github.com/flathub/flathub/pull/926#issuecomment-478556021_

**Comment by gasinvein** [comment]
If I understood it right, Lutris fails to create wineprefix inder `~/Games`, and then for some reason tries to create prefix `~/.wine` (also fails).
So this might be related to https://github.com/flathub/flathub/pull/926#issuecomment-478231140
```
2019-04-01 16:05:43,195: Creating a win64 prefix in /home/gasinvein/Games/battlenet
2019-04-01 16:05:48,473: Wine prefix creation is taking longer than expected...
2019-04-01 16:05:55,733: No user.reg found after prefix creation. Prefix might not be valid
2019-04-01 16:06:06,722: Failed to parse JSON from file /home/gasinvein/Games/battlenet/drive_c/users/gasinvein/Application Data/Battle.net/Battle.net.config
Running /home/gasinvein/.var/app/net.lutris.Lutris/data/lutris/runners/wine/tkg-4.0-x86_64/bin/wine /home/gasinvein/.var/app/net.lutris.Lutris/cache/lutris/installer/battlenet/setup/Battle.net-Setup.exe
Traceback (most recent call last):
  File "/app/bin/lutris-wrapper", line 126, in <module>
    main()
  File "/app/bin/lutris-wrapper", line 102, in main
    returncode = subprocess.run(args).returncode
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/gasinvein/.var/app/net.lutris.Lutris/data/lutris/runners/wine/tkg-4.0-x86_64/bin/wine': '/home/gasinvein/.var/app/net.lutris.Lutris/data/lutris/runners/wine/tkg-4.0-x86_64/bin/wine'
2019-04-01 16:06:12,639: No executable found at specified location /home/gasinvein/Games/battlenet/drive_c/Program Files (x86)/Battle.net/Battle.net.exe
2019-04-01 16:07:08,643: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/system32/dxgi with DXVK version
2019-04-01 16:07:08,644: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/system32/d3d11 with DXVK version
2019-04-01 16:07:08,644: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/system32/d3d10core with DXVK version
2019-04-01 16:07:08,645: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/system32/d3d10_1 with DXVK version
2019-04-01 16:07:08,645: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/system32/d3d10 with DXVK version
2019-04-01 16:07:08,646: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/syswow64/dxgi with DXVK version
2019-04-01 16:07:08,646: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/syswow64/d3d11 with DXVK version
2019-04-01 16:07:08,646: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/syswow64/d3d10core with DXVK version
2019-04-01 16:07:08,647: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/syswow64/d3d10_1 with DXVK version
2019-04-01 16:07:08,647: Replacing /home/gasinvein/Games/battlenet/drive_c/windows/syswow64/d3d10 with DXVK version
2019-04-01 16:07:19,416: Dialog hide-wine-systemwide-install-warning dismissed by user
2019-04-01 16:07:19,452: Creating a win64 prefix in /home/gasinvein/.wine
2019-04-01 16:07:24,735: Wine prefix creation is taking longer than expected...
2019-04-01 16:07:31,997: No user.reg found after prefix creation. Prefix might not be valid
2019-04-01 16:07:31,998: Unexisting registry /home/gasinvein/.wine/user.reg
2019-04-01 16:07:31,998: Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f36398dbc50>>: Invalid Wine prefix path /home/gasinvein/.wine, make sure to create the prefix before saving to a registry
<class 'OSError'> Invalid Wine prefix path /home/gasinvein/.wine, make sure to create the prefix before saving to a registry
  File "/app/lib/python3.7/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/app/lib/python3.7/site-packages/lutris/runners/wine.py", line 683, in prelaunch
    prefix_manager.configure_joypads()
  File "/app/lib/python3.7/site-packages/lutris/util/wine/prefix.py", line 159, in configure_joypads
    self.clear_registry_key(key)
  File "/app/lib/python3.7/site-packages/lutris/util/wine/prefix.py", line 54, in clear_registry_key
    registry.save()
  File "/app/lib/python3.7/site-packages/lutris/util/wine/registry.py", line 155, in save
    % prefix_path)
2019-04-01 16:07:32,173: Invalid Wine prefix path /home/gasinvein/.wine, make sure to create the prefix before saving to a registry
2019-04-01 16:07:37,523: Game prelaunch unsuccessful
```

**Comment by RobLoach** [comment]
Looks like it attempts that for the registry. Could it be [the installer](https://lutris.net/games/battlenet/) missing a prefix flag? Is Lutris applying registry changes to the incorrect prefix?

**Comment by gasinvein** [comment]
@jatin-cbs is it still reproducible with latest builds? I believe it's fixed after #21.

**Comment by Saladin1812** [comment]
Wait let me test

**Comment by Saladin1812** [comment]
Yes its fixed now you can close this

**Comment by gasinvein** [comment]
Good, closing then.
